project:
  type: website
  output-dir: www
  pre-render:
    - Rscript scripts/generate-code.R
  resources:
    - code/*.R

website:
  title: "crmPack Workshop at R/Pharma 2026"
  favicon: favicon.ico
  search: true
  navbar:
    logo: figures/logos/logo_100.png
    left:
      - href: index.qmd
        text: Home
        icon: "house-fill"
      - href: listing.qmd
        text: Slides
        icon: "file-earmark-slides"
      - href: code.qmd
        text: Code
        icon: "code-square"
    right:
      - icon: linkedin
        href: https://www.linkedin.com/company/rpact/
        aria-label: LinkedIn
      - icon: github
        href: https://github.com/rpact-com/
        aria-label: GitHub
      - icon: envelope
        href: https://www.rpact.com/contact/
        aria-label: Contact
  page-footer:
    left: |
      Copyright &copy; 2026 RPACT. All rights reserved.
    center:
      - icon: house
        text: RPACT
        href: https://www.rpact.com/ 
      - icon: envelope
        text: Contact
        href: https://www.rpact.com/contact/
    right:
      - icon: linkedin
        href: https://www.linkedin.com/company/rpact/
        aria-label: LinkedIn
      - icon: github
        href: https://github.com/rpact-com
        aria-label: GitHub

filters:
  - author-icons

format:
  html:
    theme:
    - flatly
    - custom.scss
    toc: true
    link-external-icon: false
    link-external-newwindow: true

editor: source
